Config:
  NameNodeHost: 172.19.92.94:50070
  Port: 9001
  DataNodeId: 1
  HeartbeatInterval: 6000
  # 单位 MB
  MaxSendMsgSize: 70
  MaxRecvMsgSize: 70
  HeartBeatRetry: 3
  DataDir: /temp/golanddata/trainfs/datanode
