DataNode:
  NameNodeHost: 127.0.0.1:50070
  Host: 127.0.0.1:9002
  DataNodeId: 2
  HeartbeatInterval: 6000
  HeartBeatRetry: 3
#  DataDir: /usr/projects_gen_data/goprogendata/trainfsdata/test/datanode
  DataDir: F:\ProjectsData\golang\TrainFS\DataNode
