DataNode:
  NameNodeHost: 127.0.0.1:50070
  Host: 127.0.0.1:9003
  DataNodeId: 3
  HeartbeatInterval: 6000
  HeartBeatRetry: 3
  DataDir: /usr/projects_gen_data/goprogendata/trainfsdata/test/datanode
