NameNode:
  Host: 127.0.0.1:50070
  NameNodeId: 1
  DataNodeHeartBeatInterval: 8000
  DataNodeHeartBeatTimeout: 30000
  DataDir: /usr/projects_gen_data/goprogendata/trainfsdata/test/namenode
  # model: Single | Cluster
  Model: Single
  MeIndex: 0
  PeerNameNodes: [127.0.0.1:50070,127.0.0.1:50071,127.0.0.1:50072]
